---
title: "Market_Basket_Optimization"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE}
library(arules)
library(arulesViz)
library(readr)
library(csv)

products <- read.transactions("/home/sas/Downloads/Market_Basket_Optimization.csv", sep = ',', rm.duplicates = TRUE)
summary(products)
```

```{r message=FALSE}
print(products@itemInfo)

products@itemInfo

products@data

```

```{r}
itemFrequencyPlot(products,topN=10)

summary(products)



itemFrequencyPlot(products)

```

```{r }

itemFrequencyPlot(products, topN=5)

itemFrequencyPlot(products, support = 0.1)

products.apriori <- apriori(products, parameter=list(support=0.01, confidence = 0.3,  minlen=2, maxlen =5))

summary(products.apriori)
```

```{r}

inspect(products.apriori)

inspect(sort(products.apriori, by="support")[1:10])


inspect(sort(products.apriori, by=c("support","confidence"))[1:10])

inspect(sort(products.apriori, by="lift")[1:5])

subset.matrix <- is.subset(products.apriori, products.apriori)
redundant <- colSums(subset.matrix, na.rm=T) >= 1
which(redundant)
```

```{r}

summary(products)
products.apriori.mineral_water <- apriori(products, parameter=list(support=0.01, confidence = 0.1,  minlen=2, maxlen =5),
                                     appearance = list(rhs=c("mineral water"), default = "lhs"))

inspect(sort(products.apriori.mineral_water, by="lift"))
```

```{r}

products.eclat <- eclat(products, parameter=list(support=0.003,  minlen=2, maxlen =5))
```

```{r}
summary(products.eclat)

inspect(sort(products.eclat,by='support')[1:10])

plot(products.eclat,method = "graph")
```